Repository SWM-BetterLife/AntiFragile-Android, pull requests merged in 2024-08, with the labels that each got.

#25 feat: 상단바 및 하단바 구현
  app/src/main/java/com/betterlife/antifragile/presentation/base/BaseActivity.kt
  app/src/main/java/com/betterlife/antifragile/presentation/base/BaseFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/base/ToolbarConfigurable.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/calendar/DiaryCalendarFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/DiaryRecommendEmoticonFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/DiaryTypeSelectFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmotionAnalysisFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/TextDiaryCreateFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/EmotionFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/splash/SplashActivity.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/CustomToolbar.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/DateUtil.kt
  app/src/main/res/color/bottom_nav_selector.xml
  app/src/main/res/drawable/btn_kakao_login.png
  app/src/main/res/drawable/btn_naver_login.png
  app/src/main/res/drawable/btn_type_question.xml
  app/src/main/res/drawable/btn_type_text.xml
  app/src/main/res/drawable/ic_add_diary.xml
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_calendar_active.xml
  app/src/main/res/drawable/ic_calendar_inactive.xml
  app/src/main/res/drawable/ic_content_active.xml
  app/src/main/res/drawable/ic_content_inactive.xml
  app/src/main/res/drawable/ic_emotion_active.xml
  app/src/main/res/drawable/ic_emotion_inactive.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_mypage_active.xml
  app/src/main/res/drawable/ic_mypage_inactive.xml
  app/src/main/res/drawable/ic_new_active.xml
  app/src/main/res/drawable/nav_calendar_selector.xml
  app/src/main/res/drawable/nav_content_selector.xml
  app/src/main/res/drawable/nav_emotion_selector.xml
  app/src/main/res/drawable/nav_mypage_selector.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_diary_type_select.xml
  app/src/main/res/layout/layout_toolbar.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feat

#30 feat: 텍스트 일기 수정 및 상세 조회 구현
  .idea/other.xml
  app/src/main/java/com/betterlife/antifragile/data/local/DiaryDao.kt
  app/src/main/java/com/betterlife/antifragile/data/model/common/Emotion.kt
  app/src/main/java/com/betterlife/antifragile/data/model/diary/TextDiaryDetail.kt
  app/src/main/java/com/betterlife/antifragile/data/model/diaryanalysis/response/DiaryAnalysisDailyResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/model/diaryanalysis/response/DiaryAnalysisEmoticonsResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/remote/DiaryAnalysisApiService.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/CalendarRepository.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/DiaryAnalysisRepository.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/DiaryRepository.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/EmoticonThemeRepository.kt
  app/src/main/java/com/betterlife/antifragile/presentation/base/BaseFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/customview/SelectDialog.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/calendar/DiaryCalendarFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/RecommendContentFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/DiaryTypeSelectFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmotionAnalysisFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmotionSelectFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/RecommendEmoticonFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/question/QuestionDiaryDetailFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/text/TextDiaryCreateFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/text/TextDiaryDetailFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/viewmodel/DiaryViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/viewmodel/RecommendEmoticonViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/viewmodel/TextDiaryViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/viewmodel/TextDiaryViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/EmotionFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/CustomToolbar.kt
  app/src/main/res/drawable/bg_smile_emoticon.xml
  app/src/main/res/drawable/btn_alarm.xml
  app/src/main/res/drawable/btn_edit.xml
  app/src/main/res/drawable/btn_re.xml
  app/src/main/res/layout/dialog_select.xml
  app/src/main/res/layout/fragment_text_diary_create.xml
  app/src/main/res/layout/fragment_text_diary_detail.xml
  app/src/main/res/layout/layout_toolbar.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
Labels: feat

#32 feat: 나의 감정 뷰 구현
  app/src/main/java/com/betterlife/antifragile/data/model/base/CustomErrorMessage.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/calendar/DiaryCalendarFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/EmotionFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/MyEmotionFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/MyEmotionViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/MyEmotionViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/DateUtil.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/ImageUtil.kt
  app/src/main/res/drawable/btn_rectangle_radius_100_transparent.xml
  app/src/main/res/layout/fragment_diary_calendar.xml
  app/src/main/res/layout/fragment_emotion.xml
  app/src/main/res/layout/fragment_my_emotion.xml
  app/src/main/res/layout/layout_toolbar.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat

#38 feat: my page 구현
  app/src/main/java/com/betterlife/antifragile/config/RetrofitInterface.kt
  app/src/main/java/com/betterlife/antifragile/data/model/base/CustomErrorMessage.kt
  app/src/main/java/com/betterlife/antifragile/data/model/enums/Gender.kt
  app/src/main/java/com/betterlife/antifragile/data/model/enums/LoginType.kt
  app/src/main/java/com/betterlife/antifragile/data/model/member/request/MemberProfileModifyRequest.kt
  app/src/main/java/com/betterlife/antifragile/data/model/member/response/MemberDetailResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/model/member/response/MemberProfileModifyResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/remote/MemberApiService.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/MemberRepository.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageViewModelFactory.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feat

#39 feat: 캘린더 및 감정 일기 생성 뷰 디자인 적용
  app/src/main/java/com/betterlife/antifragile/data/model/common/Emotion.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/calendar/DiaryCalendarAdapter.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/calendar/DiaryCalendarFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmotionSelectFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/adapter/EmotionSelectAdapter.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/text/TextDiaryCreateFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/text/TextDiaryDetailFragment.kt
  app/src/main/res/drawable/bg_calendar_emoticon.xml
  app/src/main/res/drawable/bg_emoticon_amazement.png
  app/src/main/res/drawable/bg_emoticon_anger.png
  app/src/main/res/drawable/bg_emoticon_anxiety.png
  app/src/main/res/drawable/bg_emoticon_depression.png
  app/src/main/res/drawable/bg_emoticon_ennui.png
  app/src/main/res/drawable/bg_emoticon_fatigue.png
  app/src/main/res/drawable/bg_emoticon_fear.png
  app/src/main/res/drawable/bg_emoticon_flutter.png
  app/src/main/res/drawable/bg_emoticon_jealousy.png
  app/src/main/res/drawable/bg_emoticon_joy.png
  app/src/main/res/drawable/bg_emoticon_normal.png
  app/src/main/res/drawable/bg_emoticon_pain.png
  app/src/main/res/drawable/bg_emoticon_panic.png
  app/src/main/res/drawable/bg_emoticon_passion.png
  app/src/main/res/drawable/bg_emoticon_sad.png
  app/src/main/res/drawable/btn_edit.xml
  app/src/main/res/drawable/btn_type_question.xml
  app/src/main/res/drawable/btn_type_text.xml
  app/src/main/res/drawable/circle_filled.xml
  app/src/main/res/drawable/ic_button_tail.xml
  app/src/main/res/drawable/ic_circle_calendar.png
  app/src/main/res/drawable/ic_circle_calendar_selected.png
  app/src/main/res/drawable/ic_emoticon_left.xml
  app/src/main/res/drawable/ic_emoticon_right.xml
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/drawable/ic_text_bubble.xml
  app/src/main/res/drawable/shape_circle.xml
  app/src/main/res/layout/fragment_diary_calendar.xml
  app/src/main/res/layout/fragment_diary_type_select.xml
  app/src/main/res/layout/fragment_emotion_select.xml
  app/src/main/res/layout/fragment_my_emotion.xml
  app/src/main/res/layout/fragment_recommend_emoticon.xml
  app/src/main/res/layout/fragment_text_diary_create.xml
  app/src/main/res/layout/fragment_text_diary_detail.xml
  app/src/main/res/layout/item_calendar.xml
  app/src/main/res/layout/item_emotion.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, refactoring

#41 feat: 내 감정 및 상&하단바 디자인 적용
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/MyEmotionFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/CustomToolbar.kt
  app/src/main/res/drawable/ic_add_diary.xml
  app/src/main/res/drawable/ic_back.png
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_no_diary_emoticon.xml
  app/src/main/res/layout/fragment_my_emotion.xml
  app/src/main/res/layout/layout_toolbar.xml
Labels: feat

#46 feat: custom 로딩 뷰 구현
  app/src/main/java/com/betterlife/antifragile/presentation/customview/CustomLoadingDialog.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmotionAnalysisFragment.kt
  app/src/main/res/drawable/emoticon_smile.xml
  app/src/main/res/layout/dialog_custom_loading.xml
  app/src/main/res/layout/fragment_emotion_analysis.xml
  app/src/main/res/values/strings.xml
Labels: feat

#52 feat: My emotion 뷰 리펙토링 및 배경 설정
  app/src/main/java/com/betterlife/antifragile/presentation/ui/calendar/DiaryCalendarFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/MyEmotionFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/MyEmotionViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageFragment.kt
Labels: feat

#47 feat: content list view
  app/src/main/java/com/betterlife/antifragile/data/local/DiaryDao.kt
  app/src/main/java/com/betterlife/antifragile/data/model/content/response/ChannelResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/model/content/response/ContentDetailResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/model/content/response/ContentListResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/model/content/response/ContentRecommendResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/model/diary/DiaryInfo.kt
  app/src/main/java/com/betterlife/antifragile/data/remote/ContentApiService.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/ContentRepository.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/DiaryRepository.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentAdapter.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentDetailFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentRecommendFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentViewCompleteFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/RecommendContentFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentDetailViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentDetailViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentRecommendViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentRecommendViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentViewCompleteViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentViewCompleteViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmoticonRecommendFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/text/TextDiaryDetailFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/DateUtil.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/ImageUtil.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/NumberUtil.kt
  app/src/main/res/drawable/btn_like_content.xml
  app/src/main/res/drawable/btn_re.xml
  app/src/main/res/drawable/btn_save_content.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_content_detail.xml
  app/src/main/res/layout/fragment_content_recommend.xml
  app/src/main/res/layout/fragment_content_view_complete.xml
  app/src/main/res/layout/fragment_recommend_content.xml
  app/src/main/res/layout/item_content.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat

#56 feat: 일기 타입 선택 뷰 수정 및 스플래시 진행바 구현
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/DiaryTypeSelectFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmoticonRecommendFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/btn_type_question_active.xml
  app/src/main/res/drawable/btn_type_question_inactive.xml
  app/src/main/res/drawable/btn_type_text_active.xml
  app/src/main/res/drawable/btn_type_text_inactive.xml
  app/src/main/res/drawable/custom_progress_bar.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_diary_type_select.xml
Labels: feat

#55 feat: my page 로직 구현
  app/src/main/java/com/betterlife/antifragile/data/model/auth/request/AuthLogoutRequest.kt
  app/src/main/java/com/betterlife/antifragile/data/model/member/response/MemberMyPageResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/remote/AuthApiService.kt
  app/src/main/java/com/betterlife/antifragile/data/remote/ContentApiService.kt
  app/src/main/java/com/betterlife/antifragile/data/remote/MemberApiService.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/ContentRepository.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/MemberRepository.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/MyPageRepository.kt
  app/src/main/java/com/betterlife/antifragile/presentation/base/BaseFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/auth/ProfileEditFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/calendar/DiaryCalendarFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentDetailFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentRecommendFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentViewCompleteFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentRecommendViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentViewCompleteViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentViewCompleteViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/viewmodel/ContentViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmoticonRecommendFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmotionSelectFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/text/TextDiaryDetailFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/viewmodel/EmoticonRecommendViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/viewmodel/EmoticonRecommendViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/emotion/MyEmotionFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageViewModelFactory.kt
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
Labels: feat

#57 feat: 일기 작성 시 LLM Inference 기능 연동
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  app/build.gradle.kts
  app/src/androidTest/java/com/betterlife/antifragile/ExampleInstrumentedTest.kt
  app/src/main/java/com/betterlife/antifragile/config/LLMTask.kt
  app/src/main/java/com/betterlife/antifragile/data/model/common/Emotion.kt
  app/src/main/java/com/betterlife/antifragile/data/model/common/LLMInferenceType.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/LLMRepository.kt
  app/src/main/java/com/betterlife/antifragile/presentation/base/BaseFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmotionAnalysisFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/viewmodel/DiaryViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/viewmodel/LLMViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/viewmodel/LLMViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/line.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/fragment_diary_type_select.xml
  app/src/main/res/layout/fragment_emotion_analysis.xml
  app/src/main/res/layout/fragment_my_emotion.xml
  app/src/main/res/layout/fragment_question_diary_detail.xml
  app/src/main/res/layout/fragment_term_detail.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/file_paths.xml
  app/src/test/java/com/betterlife/antifragile/ExampleUnitTest.kt
Labels: feat

#60 refactor: 약관 동의 내용 작성
  app/src/main/java/com/betterlife/antifragile/data/model/enums/TermType.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/auth/TermDetailFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/auth/TermsFragment.kt
  app/src/main/res/layout/fragment_term_detail.xml
  app/src/main/res/layout/fragment_terms.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#61 feat: mvp1을 위한 세팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/betterlife/antifragile/config/LLMTask.kt
  app/src/main/java/com/betterlife/antifragile/config/RetrofitInterface.kt
  app/src/main/java/com/betterlife/antifragile/data/model/common/Emotion.kt
  app/src/main/java/com/betterlife/antifragile/data/model/enums/MemberStatus.kt
  app/src/main/java/com/betterlife/antifragile/data/model/llm/DiaryAnalysisData.kt
  app/src/main/java/com/betterlife/antifragile/data/model/llm/LlmModelUrlResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/model/member/response/MemberDetailResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/model/member/response/MemberExistenceResponse.kt
  app/src/main/java/com/betterlife/antifragile/data/remote/AuthApiService.kt
  app/src/main/java/com/betterlife/antifragile/data/remote/LlmModelApiService.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/CalendarRepository.kt
  app/src/main/java/com/betterlife/antifragile/data/repository/LLMModelRepository.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/auth/LoginFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/auth/ProfileEditFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/calendar/DiaryCalendarFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/calendar/viewmodel/DiaryCalendarViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/content/ContentFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmoticonRecommendFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmotionAnalysisFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/EmotionSelectFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/diary/text/TextDiaryCreateFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/splash/SplashActivity.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/splash/SplashViewModel.kt
  app/src/main/java/com/betterlife/antifragile/presentation/ui/splash/SplashViewModelFactory.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/ModelDownloader.kt
  app/src/main/java/com/betterlife/antifragile/presentation/util/SimpleTextWatcher.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_content.xml
  app/src/main/res/layout/fragment_content_recommend.xml
  app/src/main/res/layout/fragment_diary_calendar.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
Labels: feat, fix

#62 feat: App Logo 적용
  app/src/main/AndroidManifest.xml
  app/src/main/ic_main-playstore.png
  app/src/main/res/drawable/ic_main_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main_round.xml
  app/src/main/res/mipmap-hdpi/ic_main.webp
  app/src/main/res/mipmap-hdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_main_round.webp
  app/src/main/res/mipmap-mdpi/ic_main.webp
  app/src/main/res/mipmap-mdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_main_round.webp
  app/src/main/res/mipmap-xhdpi/ic_main.webp
  app/src/main/res/mipmap-xhdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_main_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_main.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_round.webp
Labels: feat
